bootstrap.servers:
client.id: ClientID

acks: Producer.RequiredAcks
batch.size: Producer.Flush.Bytes
compression.type: Producer.Compression
linger.ms: Producer.Flush.Frequency
max.in.flight.requests.per.connection: Net.MaxOpenRequests
retries: Producer.Retry.Max

:
  - Producer.Flush.Messages
  - ChannelBufferSize

delivery.timeout.ms: Net.ReadTimeout + Net.WriteTimeout
request.timeout.ms: Producer.Timeout

buffer.memory:
max.block.ms:
max.request.size:

kt-dev admin -createtopic test -topicdetail <(jsonify =NumPartitions 6 =ReplicationFactor 3 =ConfigEntries $(jsonify -retention.ms 60000 -segment.bytes 104857600 -retention.bytes 1073741824 -file.delete.delay.ms 1000))